[project]
name = "word-generator"
version = "0.1.0"
description = ""
authors = [
    {name = "ignius299792458"}
]
requires-python = ">=3.12"
dependencies = [
    "torch (>=2.13.0,<3.0.0)",
    "numpy (>=2.5.2,<3.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)"
]


[tool.poetry]
packages = [{include = "word_generator"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)"
]
