[project]
name = "word-generator"
version = "0.1.0"
description = ""
authors = [
    {name = "ignius299792458"}
]
requires-python = ">=3.12"
dependencies = [
]


[tool.poetry]
packages = [{include = "word-generator"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
